server:
  port: 8082
spring:
  application:
    name: ad-gateway



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

zuul:
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: ad-sponsor
      strip-prefix: false